config/routes.rb
HappyNewYear::Application.routes.draw do
  post "specials/verify"
  get "pages/main"

  root 'pages#main', as: 'home'
  get "/happy_new_year", to: "specials#congratulate", as: "congrats"

  

end

app/models/special.rb
class Special < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  before_filter :check_name, except: :verify

  def verify
    verify_name = params[:special][:name]
    if Special.where(name: verify_name).exists?
      session[:special] = Special.where(name: verify_name).first.name
      redirect_to congrats_path
    else
      redirect_to home_path
    end

  end

  def congratulate

  end

  def check_name
    unless session[:special] == Special.first.name
      redirect_to home_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Happy New Year!</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name"><h1><a href="#"><%= content_for?(:title)? yield(:title) : "Кто мой самый дорогой человек?" %></a></h1></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->

      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-form">
          <div class="row collapse">
            <%= render 'specials/form' %>
          </div>
        </li>
      </ul>
    </section>
  </nav>
  <header>
      <div class="row">
          <div class="large-6 large-offset-3 columns">
          <img src="<%= asset_path( 'New_Year_2014_Image.jpg' ) %>" /></div>
      </div>
    </header>
    <section class="main">
      <%= yield %>
    <%= javascript_include_tag "application" %>
    </section>

  </body>
</html>

app/views/specials/_form.html.erb
<%= form_for :special, url: specials_verify_path do |f| %>
    <div class="large-8 small-9 columns"><%= f.text_field :name, placeholder: "Введи свое имя" %><!--<input type="text" placeholder="Enter your name">-->
    </div>
    <div class="large-4 small-3 columns">
      <%= f.submit "Это я", class: "alert button expand" %><!--<a href="#" class="alert button expand">Confirm</a>-->
    </div>
<% end %>

app/views/specials/congratulate.html.erb
<div class="large-3 columns" style="padding-top:10px;">
      <audio controls>
        <source src="Fall Out Boy - We wish you a marry christmas And A Happy New Year.mp3" type="audio/mpeg">
        <embed height="50" width="50" src="Fall Out Boy - We wish you a marry christmas And A Happy New Year.mp3">

      </audio>
      <hr />
      <h3>Fall Out Boy поздравляет тебя с Новым Годом!</h3>


  </div>
<div class="congrats large-6 columns">

  <div id="pic" style="display:none"><img src="<%= asset_path('Dima.jpg') %>"/>
  </div>

</div>

<div class="large-3 columns" style="padding-top:10px;">
  <a href=""><h2 id="wish">Димушек, <br />я желаю тебе...</h2></a>
  <ul  id="wishes" style="display:none">
    <li class="fancy_title">Успеха</span></li>
    <li class="fancy_title">Здоровья</li>
    <li class="fancy_title">Радости</li>
    <li class="fancy_title">Нежности</li>
    <li class="fancy_title">Обнимашек</li>
    <li class="fancy_title">Вкусняшек</li>
    <li class="fancy_title">Денег</li>
    <li class="fancy_title">Власти над миром</li>
    <!--<li class="fancy_title">Удачи</li>
    <li class="fancy_title">Преданных друзей</li>
    <li class="fancy_title">Полезных знакомств</li>
    <li class="fancy_title">Отличного настроения</li>
    <li class="fancy_title">Увлекательных путешествий</li>
    <li class="fancy_title">Комфорта</li>
    <li class="fancy_title">Развития</li>-->
    <li class="fancy_title">Счастья</li>
  </ul>
</div>
<div id="hexaflip-demo1" class="demo"></div>



<% content_for :title do %>
   Это именно ты! :**
<% end %>

app/views/specials/verify.html.erb
<h1>Specials#verify</h1>
<p>Find me in app/views/specials/verify.html.erb</p>
<%= @special.name %>